services:
  postgres:
    image: postgres:14
    container_name: fit-trackr-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fit_trackr
    ports:
      - "5433:5432"  # Cambiado a 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fit-trackr-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fit-trackr-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fit-trackr-network

networks:
  fit-trackr-network:
    driver: bridge

volumes:
  postgres_data: